// apps/web/src/App.svelte
<script lang="ts">
    import { createTRPCProxyClient, httpBatchLink } from "@trpc/client"
    import viteLogo from "/vite.svg"
    import type { AppRouter } from "../../api/src/trpc/router.ts"
    import svelteLogo from "./assets/svelte.svg"
    import Counter from "./lib/Counter.svelte"

    const client = createTRPCProxyClient<AppRouter>({
        links: [
            httpBatchLink({
                url: "/trpc",
            }),
        ],
    })

    alert(await client.hello.query("Hono"))
</script>

<main>
    <div>
        <a href="https://vite.dev" target="_blank" rel="noreferrer">
            <img src={viteLogo} class="logo" alt="Vite Logo" />
        </a>
        <a href="https://svelte.dev" target="_blank" rel="noreferrer">
            <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
        </a>
    </div>
    <h1>Vite + Svelte</h1>

    <div class="card">
        <Counter />
    </div>

    <p>
        Check out <a
            href="https://github.com/sveltejs/kit#readme"
            target="_blank"
            rel="noreferrer">SvelteKit</a
        >, the official Svelte app framework powered by Vite!
    </p>

    <p class="read-the-docs">
        Click on the Vite and Svelte logos to learn more
    </p>
</main>

<style>
    .logo {
        height: 6em;
        padding: 1.5em;
        will-change: filter;
        transition: filter 300ms;
    }
    .logo:hover {
        filter: drop-shadow(0 0 2em #646cffaa);
    }
    .logo.svelte:hover {
        filter: drop-shadow(0 0 2em #ff3e00aa);
    }
    .read-the-docs {
        color: #888;
    }
</style>

// apps/web/src/App.tsx
import { useState, useEffect } from "react"
import {
    SignedIn,
    SignedOut,
    SignInButton,
    UserButton,
} from "@clerk/clerk-react"
import { createTRPCProxyClient, httpBatchLink } from "@trpc/client"
import reactLogo from "./assets/react.svg"
import viteLogo from "/vite.svg"
import "./App.css"
import type { AppRouter } from "../../api/src/trpc/router.ts"

const client = createTRPCProxyClient<AppRouter>({
    links: [
        httpBatchLink({
            url: "/trpc",
        }),
    ],
})

function App() {
    const [count, setCount] = useState(0)

    useEffect(() => {
        async function fetchHello() {
            const result = await client.hello.query("Hono")
            alert(result)
        }
        fetchHello()
    }, [])

    return (
        <>
            <header>
                <SignedOut>
                    <SignInButton />
                </SignedOut>
                <SignedIn>
                    <UserButton />
                </SignedIn>
            </header>
            <div>
                <a href="https://vite.dev" target="_blank" rel="noreferrer">
                    <img src={viteLogo} className="logo" alt="Vite logo" />
                </a>
                <a href="https://react.dev" target="_blank" rel="noreferrer">
                    <img
                        src={reactLogo}
                        className="logo react"
                        alt="React logo"
                    />
                </a>
            </div>
            <h1>Vite + React</h1>
            <div className="card">
                <button onClick={() => setCount((count) => count + 1)}>
                    count is {count}
                </button>
                <p>
                    Edit <code>src/App.tsx</code> and save to test HMR
                </p>
            </div>
            <p className="read-the-docs">
                Click on the Vite and React logos to learn more
            </p>
        </>
    )
}

export default App
